### ISSUE TITLE
error while starting server.js

### ISSUE THREAD

**Issue by oblamine** [randerzander/node-phoenix#1]
Hello, i m facing this issue while i try to execute sudo node server.js

/home/datanode/node-phoenix/node_modules/jdbc/lib/pool.js:64
  this._url = config.url;
            ^

TypeError: Cannot set property '_url' of undefined
    at Pool (/home/datanode/node-phoenix/node_modules/jdbc/lib/pool.js:64:13)
    at JDBC (/home/datanode/node-phoenix/node_modules/jdbc/lib/jdbc.js:6:8)
    at Object.<anonymous> (/home/datanode/node-phoenix/server.js:12:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
thanks for helping :)

**Comment by YoucefChihi** [comment]
If you're using a recent version of jdbc, you should probably try this:

var JDBC = require('jdbc');

var config = {
  libpath: '/usr/hdp/current/phoenix-client/phoenix-client.jar',
  drivername: 'org.apache.phoenix.jdbc.PhoenixDriver',
  url: 'jdbc:phoenix:namenode:2181:/hbase-unsecure',
  properties: { 
    user: '', 
    password: '' 
  } 
}

jdbc = new JDBC(config)

//Initialize jdbc object
jdbc.initialize(function(err){ if (err){ console.log(err); } });

jdbc.open...
