### ISSUE TITLE
Could not find class org.apache.phoenix.jdbc.PhoenixDriver

### ISSUE THREAD

**Issue by YoucefChihi** [randerzander/node-phoenix#3]
Error: Could not find class org.apache.phoenix.jdbc.PhoenixDriver
java.lang.NoClassDefFoundError: org/apache/phoenix/jdbc/PhoenixDriver
Caused by: java.lang.ClassNotFoundException: org.apache.phoenix.jdbc.PhoenixDriver
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

    at Error (native)
    at JDBC.Pool.initialize (/home/youcef/graph/node_modules/jdbc/lib/pool.js:135:10)

**Comment by Nocturnal316** [comment]
did you get this working?

**Comment by YoucefChihi** [comment]
Yes but not using this package, I got around it by using node-jdbc
